# Generated by Django 5.0.6 on 2026-02-03 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('validacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='html_generados/')),
                ('etiquetasSemanticas', models.TextField(blank=True)),
                ('nivelAccesibilidad', models.CharField(default='A (Básico)', max_length=50)),
                ('cantidadEtiquetas', models.IntegerField(default=0)),
                ('lenguajeHTML', models.CharField(default='es', max_length=5)),
                ('documento_fuente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='html_generado', to='validacion.documentopdf')),
            ],
        ),
        migrations.CreateModel(
            name='ConversorFormato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatoDestino', models.CharField(default='HTML', max_length=10)),
                ('fechaConversion', models.DateTimeField(auto_now_add=True)),
                ('tiempoEjecucion', models.FloatField(blank=True, null=True)),
                ('documento_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.documentopdf')),
            ],
        ),
    ]
