# Generated by Django 5.0.6 on 2026-02-04 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
        ('validacion', '0002_esquemaidentificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoEPUB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadatosAccesibilidad', models.TextField()),
                ('esquemaValidacion', models.CharField(max_length=100)),
                ('incluyeNavegacion', models.BooleanField()),
                ('recursosIncluidos', models.TextField()),
                ('documento_fuente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='validacion.documentopdf')),
            ],
        ),
        migrations.CreateModel(
            name='AccionPropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando_tecnico', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversion.plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversion.protocolo'),
        ),
    ]
