# Generated by Django 5.0.6 on 2026-04-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_plan_protocolo_archivoepub_accionpropuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversorformato',
            name='token_acceso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
