version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_backend
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py migrate &&
             gunicorn djangoProject1.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - media_data:/app/media    # ✅ Comparte media con nginx

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    expose:
      - "80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - media_data:/app/media:ro  # ✅ Nginx lee media en modo solo lectura
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  media_data:
  reportes_data: