# Generated by Django 5.0.6 on 2026-02-04 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversion', '0002_plan_protocolo_archivoepub_accionpropuesta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('tasa_exito_elementos', models.FloatField(help_text='Porcentaje de objetos identificables convertidos con éxito')),
                ('puntuacion_accesibilidad', models.IntegerField(default=0)),
                ('cumple_estandar_unl', models.BooleanField(default=False)),
                ('conclusiones_tecnicas', models.TextField(blank=True)),
                ('conversor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_resultado', to='conversion.conversorformato')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoIdentificable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_objetivo', models.CharField(max_length=255)),
                ('logrado', models.BooleanField(default=False)),
                ('referencia_objeto_id', models.IntegerField(blank=True, null=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_calidad', to='reportes.reportetecnico')),
            ],
        ),
        migrations.CreateModel(
            name='ResumenEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fenomenos_detectados', models.IntegerField(default=0)),
                ('total_acciones_mitigacion_ejecutadas', models.IntegerField(default=0)),
                ('tiempo_procesamiento_segundos', models.FloatField()),
                ('memoria_utilizada', models.CharField(blank=True, max_length=50)),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reportes.reportetecnico')),
            ],
            options={
                'verbose_name_plural': 'Resúmenes de Ejecución',
            },
        ),
    ]
