# Generated by Django 5.0.6 on 2026-02-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.FileField(upload_to='docs/')),
                ('tamanio', models.FloatField(default=0.0)),
                ('fechaCarga', models.DateTimeField(auto_now_add=True)),
                ('numeroPaginas', models.IntegerField(default=0)),
                ('tieneEtiquetas', models.BooleanField(default=False)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
            ],
        ),
    ]
