# Generated by Django 5.0.6 on 2026-02-04 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsquemaIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('formato_regex', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='documentopdf',
            old_name='fechaCarga',
            new_name='fecha_subida',
        ),
        migrations.AddField(
            model_name='documentopdf',
            name='tipoContenido',
            field=models.CharField(choices=[('TEXTUAL', 'Textual'), ('MIXTO', 'Mixto'), ('IMAGEN', 'Imagen (Escaneado)')], default='TEXTUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentopdf',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('CONVERTIDO', 'Convertido'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentopdf',
            name='tamanio',
            field=models.FloatField(default=0.0, help_text='Tamaño en KB'),
        ),
        migrations.CreateModel(
            name='ObjetoIdentificable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_elemento', models.CharField(max_length=50)),
                ('posicion_x', models.FloatField()),
                ('posicion_y', models.FloatField()),
                ('pagina', models.IntegerField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='validacion.documentopdf')),
            ],
        ),
        migrations.CreateModel(
            name='Identificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.esquemaidentificacion')),
                ('objeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_oficial', to='validacion.objetoidentificable')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('detalleTecnico', models.TextField()),
                ('faseOrigen', models.CharField(max_length=100)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='validacion.documentopdf')),
            ],
        ),
    ]
