# Generated by Django 5.0.6 on 2026-02-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0002_esquemaidentificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidadorAccesibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_herramienta', models.CharField(max_length=50)),
                ('resultado_texto', models.TextField(blank=True)),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='validacion.documentopdf')),
            ],
        ),
    ]
