name: Security Audit (Gitleaks)

on:
  push:
    branches: [ main, master, feature]
  pull_request:
    branches: [ main, master, feature ]
  workflow_dispatch:

jobs:
  gitleaks:
    name: Secret Scanning Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks Scan
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          report-format: sarif
          report-path: results.sarif

      - name: Upload Security Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: results.sarif